
services:
  db:
    image: postgres
    container_name: cloudstack-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: cloudstack
    ports:
      - "5432:5432"  # use default port for clarity
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: cloudstack-backend
    depends_on:
      - db
    volumes:
      - ./backend:/app
    working_dir: /app
    tty: true
    ports:
      - "5050:5000"
    environment:
      - DB_NAME=cloudstack
      - DB_USER=postgres
      - DB_PASSWORD=secret
      - DB_HOST=db
      - DB_PORT=5432
      - CS_ENV=prod  # optional custom environment flag (CS==CloudStack for reference)


  frontend:
    build:
      context: ./frontend
    container_name: cloudstack-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  nginx:
#    image: nginx
    image: nginx:1.27
    container_name: cloudstack-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./frontend/out:/usr/share/nginx/html:ro
    depends_on:
      - backend

volumes:
  pgdata:
